--USER 1
DBCC USEROPTIONS;

SELECT * FROM BANK;

BEGIN TRAN
	UPDATE BANK
	SET BALANCE = 999999
	WHERE CID = 10;

	WAITFOR DELAY '00:00:10'
	COMMIT;
	SELECT * FROM BANK;

-- SELECT IS NOT A TRANSACTION

BEGIN TRAN
	SELECT * FROM BANK;

	WAITFOR DELAY '00:00:02'
	UPDATE BANK
	SET BALANCE = 88888
	WHERE CID = 10;
	COMMIT; 

BEGIN TRAN
	SELECT * FROM BANK;

	WAITFOR DELAY '00:00:10'
	UPDATE BANK
	SET BALANCE = 88888
	WHERE CID = 10;
	COMMIT;
	SELECT * FROM BANK;  -- NOW NEW RESULT