SELECT * FROM EMPLOYEES;

SELECT * 
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

SELECT * 
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

-- DYNAMIC SQL
DECLARE @sql NVARCHAR(MAX)
--MAX STANDS FOR 4000 CHARACTERS
DECLARE @paramlist NVARCHAR(MAX)

SET @sql = N'SELECT *
			FROM EMPLOYEES
			WHERE DEPARTMENT_ID = @DID;'
SET @paramlist = N'@DID INT'
EXEC SP_EXECUTESQL @sql, @paramlist, @DID = 20;

--2 PARAMETERS
DECLARE @sql NVARCHAR(MAX)
DECLARE @paramlist NVARCHAR(MAX)

SET @sql = N'SELECT *
			FROM EMPLOYEES
			WHERE DEPARTMENT_ID = @DID AND SALARY> @SAL;'
SET @paramlist = N'@DID INT, @SAL FLOAT'
EXEC SP_EXECUTESQL @sql, @paramlist, @DID = 50, @SAL = 5000;


DECLARE @sql NVARCHAR(MAX)
DECLARE @paramlist NVARCHAR(MAX)

SET @sql = N'SELECT *
			FROM EMPLOYEES
			WHERE (DEPARTMENT_ID = @DID AND @SAL > 5000) OR JOB_ID = @JID;'
SET @paramlist = N'@DID INT, @SAL FLOAT, @JID VARCHAR(100)'
EXEC SP_EXECUTESQL @sql, @paramlist, @DID = 50, @SAL = 5000, @JID = 'IT_PROG';
