--USER 2

SELECT * FROM BANK;
-- READ COMMITTED
SELECT * FROM BANK(NOLOCK);
-- NOLOCK OR READ UNCOMMITTED- CAUSES DIRTY READ PROBLEM
--OR
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED --FOR ALL THE QUERIES IN THE SESSION
DBCC USEROPTIONS;
