USE IVP3686;

SELECT * FROM SYS.SCHEMAS;
CREATE SCHEMA MiniProject;

CREATE TABLE MiniProject.Stream
(
	StreamID INT IDENTITY(1,1) CONSTRAINT Stream_StreamID_PK PRIMARY KEY,
	StreamName VARCHAR(10) CONSTRAINT Stream_StreamName_CK 
	CHECK(StreamName IN ('CS', 'IT', 'EXTC', 'ELECT', 'MECH')) NOT NULL
);


CREATE TABLE MiniProject.Student 
(
	SID INT IDENTITY(1000,1) CONSTRAINT Student_SID_PK PRIMARY KEY,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	Email VARCHAR(25) CONSTRAINT Student_Email_UK UNIQUE,
	StreamID INT CONSTRAINT Student_StreamID_FK FOREIGN KEY REFERENCES MiniProject.Stream(StreamID), 
	Grade CHAR(1) CONSTRAINT Student_Grade_CK CHECK(GRADE IN ('A', 'B', 'C', 'D', 'F')) NOT NULL,
	Marks FLOAT CONSTRAINT Student_Marks_CK CHECK(Marks BETWEEN 0 AND 	100),
	AdmissionDate DATETIME CONSTRAINT Student_AdmissionDate_CK CHECK(AdmissioNDate<= GETDATE()) NOT NULL
);


CREATE TABLE MiniProject.HOD
(
	HODID VARCHAR(20) CONSTRAINT HOD_ID_PK PRIMARY KEY 
	CONSTRAINT HOD_ID_CK CHECK(HODID LIKE 'IVP[0-9][0-9][0-9]'),
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	Email VARCHAR(25) CONSTRAINT HOD_Email_UK UNIQUE,
	StreamId INT CONSTRAINT HOD_StreamID_FK FOREIGN KEY REFERENCES MiniProject.Stream(StreamID),
	HireDate DATETIME NOT NULL CONSTRAINT HOD_HireDate_CK CHECK(HireDate <= GETDATE())  
);

CREATE TABLE MiniProject.Administrator
(
	AdminID CHAR(5) CONSTRAINT Admin_ID_PK PRIMARY KEY CONSTRAINT Admin_ID_CK CHECK(AdminID LIKE 'MS[0-9][0-9][0-9]'),
	AdminName VARCHAR(50) NOT NULL CONSTRAINT Admin_Name_CK CHECK(AdminName = UPPER(AdminName)),
	UserID VARCHAR(50) NOT NULL CONSTRAINT Admin_UserID_UK UNIQUE,
	Password VARCHAR(50) NOT NULL CONSTRAINT Admin_Pwd_CK CHECK(LEN(Password) >= 8),
	AdminContact VARCHAR(50) NOT NULL CONSTRAINT Admin_Contact_UK UNIQUE,
	AdminEmail VARCHAR(50) NOT NULL CONSTRAINT Admin_Email_UK UNIQUE
);

